---
title: "Police Shootings in the United States: A Data-Based Perspective"
author: "Amy Latimer, Krystal Liang, Ashley Varma"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
runtime: shiny
---
```{R setup, include=FALSE}
  library(shiny)
  library(prettydoc)
  library(dplyr)
  library(ggplot2)
  library(plotly)
  library(dygraphs)
  library(xts)
  source("krystalquestion.R")
  source("Amy Data Wrangling.R")
```

###Is there a relationship between the socioeconomic status of a county and the number of fatal police shootings in that county? 

Below is an interactive visualization of police shootings from 2015 distributed by various social and economic factors. It takes the form of a histogram, which shows the count of the data falling into each ' _bin_ on the x-axis. Histograms are excellent for revealing potential cause and effect relationships in data.
```{R vis1, echo=FALSE}
select.options <- c('County Income (USD)', 'Tract level unemployment rate (%)', 'Bachelor Degree or Higher', 'Tract level poverty rate (%)', '% White, County Level', '% Black, County Level', '% Hispanic, County Level')
options.graph <- c('county_income', 'urate', 'college', 'pov', 'share_white', 'share_black', 'share_hispanic')
police.killings.short <- select(police.killings, options.graph)
police.killings.short$pov <- suppressWarnings(as.numeric(as.character(police.killings.short$pov)))
police.killings.short$share_white <- suppressWarnings(as.numeric(as.character(police.killings.short$share_white)))
police.killings.short$share_black <- suppressWarnings(as.numeric(as.character(police.killings.short$share_black)))
police.killings.short$share_hispanic <- suppressWarnings(as.numeric(as.character(police.killings.short$share_hispanic)))
colnames(police.killings.short) <- select.options

census.data <- c(55322, .07, .303, 15.9, 61.3, 13.3, 17.8)
census.data.frame <- data.frame(select.options, census.data)
                    
# Define UI for application that draws a histogram
ui <- fluidPage (
   titlePanel('Distributions'),
   sidebarLayout(
      sidebarPanel(
         selectInput('option', 'Police killings based on:', select.options, multiple = FALSE)
      ),
      mainPanel(
         plotOutput("distPlot", height = "325px")
      )
   )
)

server <- function(input, output) {
   output$distPlot <- renderPlot({
      x.int <- census.data.frame[census.data.frame$select.options==input$option, 2]
      ggplot(data=police.killings.short, aes(select(police.killings.short, input$option))) + 
        geom_histogram(aes(y = ..count..), bins = 10, colour = 'black',
                       fill = "LightBlue") +
        labs(x = input$option, y = "Count") +
        geom_vline(xintercept = x.int, linetype ='dashed', 
                   color = 'black', size = 1)
   })
}

shinyApp(ui = ui, server = server)
```



*************************************************************


###How do race and ethnicity relate to the number of police killings in the United States?

```{R vis3, echo=FALSE}
bar.graph
```
**Hover over the bars to view how many were killed for each racial demographic**

Noticeably, this graph shows that whites were killed more often than any minority. This finding does not fit with current conversations relating to police violence, which often claim that minorities are disproportionately affected by police killings. This graph must be supplemented with United States Census data to understand the full picture, or it is otherwise misleading. 

Below is table of the nation's racial demographics [according to census data from 2016](https://www.census.gov/quickfacts/fact/table/US#viewtop).

Race/Ethnicity | Percentage of the Population
:---:|:----:
American Indian/Alaskan Native alone | 1.3%
Asian alone | 5.7%
Hawaiian/Pacific Islander | 0.2%
Black/African American | 13.3%
White alone (not Hispanic/Latino) | 61.3%

Although people of color make up 39% of the United States population, they accounted for 48% of fatal police shootings in 2015. This difference of 9% is _disproportionately more_ than their demographic. Based on this analysis alone there seems to be merit to an idea portrayed nearly univerally in the media, without much evidence: that people of color are more often at the receving end of police brutality than white people. 


*************************************************************


###How does the average poverty rate for a state relate to the number of police killings in that state?

```{R vis4, echo=FALSE}
p
```
**Hover a state to view how many were killed and the average poverty rate for that state. The red dots are the locations of fatal police shootings.**


*************************************************************
###Have the number of police killings changed in the past few years?

The answer to that question, tragically, is **no**. Below is an interactive plot of all fatal police shootings from 2015-present. Steadily, there have been about 30 police killings per month since 2015. The deaths of Philando Castile and Eric Garner are marked below, and not even the nation-wide outcry against those deaths had a measurable affect on police shootings.  

```{R vis5, echo=FALSE}
monthly.killings
```


*************************************************************

