---
title: "Police Killings"
author: "Amy Latimer, Krystal Liang, Ashley Varma"
date: "3/1/2018"
output: html_document
runtime: shiny
---

```{R setup, echo=FALSE, message=FALSE}
  library(shiny)
  library(dplyr)
  library(ggplot2)
  source('Question 1.R/app.R')
  source("krystalquestion.R")
```

###Is there a relationship between the socioeconomic status of a county and
###the number of police killings in that county? 

```{R vis1, echo=FALSE}
select.options <- c('County Income', 'Unemployment Rate', 'Bachelor Degree or Higher', 'Percent White', 'Percent Black', 'Percent Hispanic')
options.graph <- c('county_income', 'urate', 'college','share_white', 'share_black', 'share_hispanic')
name.frame <- data.frame(select.options, options.graph)
                    
# Define UI for application that draws a histogram
ui <- fluidPage (
   titlePanel('Distributions'),
   sidebarLayout(
      sidebarPanel(
         selectInput('option', 'Police killings based on:', select.options, multiple = FALSE),
         radioButtons('plot', 'Display as:', choices = 'Histogram')
      ),
      mainPanel(
         plotOutput("distPlot")
      )
   )
)

server <- function(input, output) {
   output$distPlot <- renderPlot({
      aes <- filter(name.frame, select.options==!!as.name(input$option))
      aes <- aes[1, 2]
      ggplot(data=police.killings, paste0('police.killings$', aes)) + 
        geom_histogram(aes(y = ..count..), bins = 9, colour = 'grey',
                       fill = 'red') +
        labs(x = "Median County Income (USD)", y = "Count") +
        geom_vline(xintercept = 57230, linetype ='dashed', 
                   color = 'black', size = 1)
   })
}

shinyApp(ui = ui, server = server)
```

###How does race and ethnicity relate to the number of people killed in the United States?
```{R vis3, echo=FALSE}
bar.graph
```

You may think at first when you are viewing this visualization, "the graph shows that more white people were killed altogether". However, this is where the graph is misleading if you don't have all the information you need about how the numbers in the graph are proportionate to the percent population of those specific races/ethnicities.

According to the United States Census Bureu data, in 2017, the estimated population for the 
country was 325,719,178 people. [According to the 2016 census data](https://www.census.gov/quickfacts/fact/table/US#viewtop)

Race/Ethnicity | Percentage of the Population
:---:|:----:
American Indian/Alaskan Native alone | 1.3%
Asian alone | 5.7%
Hawaiian/Pacific Islander | 0.2%
Black/African American | 13.3%
White alone (not Hispanic/Latino) | 61.3%

If you add up the values for people of color and compare that number to people who are white alone, ignoring the "unknown" column, you can see that the numbers are pretty close at **216 People of Color** vs **236 People who were White alone**. This is important to note because this reveals that more people of color were actually killed altogether in all of the US compared to people who are white alone. Since the population of white people are higher, less white people were killed altogether. This conclusion correlates to what the media displays as well. There seems to always be more talk about the death of people of color compared to white people when it comes to gun violence in America.

###How does the average poverty rate (calculated by averaging the tract level poverty rate ###(rate for smaller areas of a bigger county)) for each state correlate to the amount of ###killings present in each state?

```{R vis4, echo=FALSE}
p

```



